#!/bin/bash

# This script is to make warps for registration.
# Following files are necessary:
#    Tractography.bedpostX <== generated by bedpostx
#    nodif_brain.nii.gz <== generated by bedpsotx
#    nifti_data/*T1*.nii(T1 nifti_file) <== generated by dcm2niix

# get ImageID and change directory
ImageID=$(basename $FPATH)
cd $FPATH

# get T1w from nifti_data directory (assuming 1 or more T1w with name of *T1* exists), if there is no T1w, exit.
T1w=$(find ./nifti_data -name \*T1*.nii -print | sed -n 1p)
if [[ -z $T1w ]]; then
    echo " There seems no T1w in nifti_data."
    exit 1
fi

# bet
echo "Now running bet..."
cp $T1w DWI/T1.nii
cd DWI
gzip T1.nii
bet T1.nii.gz T1_brain.nii.gz -f 0.2 -R -S -B
date

# prepare files
mv Tractography.bedpostX/ DTI.bedpostX/
mv nodif_brain.nii.gz DTI.bedpostX/
date

# registration
echo "Now running flirt..."
flirt -in DTI.bedpostX/nodif_brain \
    -ref T1_brain.nii.gz \
    -omat DTI.bedpostX/xfms/diff2str.mat \
    -searchrx -180 180 -searchry -180 180 -searchrz -180 180 \
    -dof 6 -cost corratio

convert_xfm -omat DTI.bedpostX/xfms/str2diff.mat \
    -inverse DTI.bedpostX/xfms/diff2str.mat

flirt -in T1_brain.nii.gz \
    -ref /usr/local/fsl/data/standard/MNI152_T1_2mm_brain.nii.gz \
    -omat DTI.bedpostX/xfms/str2standard.mat \
    -searchrx -180 180 -searchry -180 180 -searchrz -180 180 \
    -dof 12 -cost corratio
date
echo "Now running fnirt..."

convert_xfm -omat DTI.bedpostX/xfms/standard2str.mat \
            -inverse DTI.bedpostX/xfms/str2standard.mat
 
convert_xfm -omat DTI.bedpostX/xfms/diff2standard.mat \
            -concat DTI.bedpostX/xfms/str2standard.mat DTI.bedpostX/xfms/diff2str.mat
 
convert_xfm -omat DTI.bedpostX/xfms/standard2diff.mat \
            -inverse DTI.bedpostX/xfms/diff2standard.mat

fnirt --in=T1.nii.gz \
    --aff=DTI.bedpostX/xfms/str2standard.mat \
    --cout=DTI.bedpostX/xfms/str2standard_warp \
    --config=T1_2_MNI152_2mm
date
echo "Now running invwarp..."
invwarp -w DTI.bedpostX/xfms/str2standard_warp \
        -o DTI.bedpostX/xfms/standard2str_warp \
        -r T1_brain.nii.gz 

convertwarp -o DTI.bedpostX/xfms/diff2standard_warp \
    -r /usr/local/fsl/data/standard/MNI152_T1_2mm_brain.nii.gz \
    -m DTI.bedpostX/xfms/diff2str.mat \
    -w DTI.bedpostX/xfms/str2standard_warp

convertwarp -o DTI.bedpostX/xfms/standard2diff_warp \
    -r DTI.bedpostX/nodif_brain_mask \
    -w DTI.bedpostX/xfms/standard2str_warp \
    --postmat=DTI.bedpostX/xfms/str2diff.mat
cd ..

exit
